### PR TITLE
Add French language support.

### PR DESCRIPTION
**Pull request by hobbe**

### CODE REVIEW

**Comment by bhawker** [comment]
Thank you for the pull request @hobbe! I will merge this in for an upcoming release shortly, along with Spanish translations.

I just added Egg Timer support for many other watches, so that label is slightly different for these watches. If possible, would you be able to translate these similar sentences as well?

1) **Hold Up** button to start new timer
2) **Hold Right** button to start new timer
3) **Press and hold** to start new timer


Thank you!
Brandon

**Comment by hobbe** [comment]
Hi @bhawker 

Not sure in which context, on which screen and on which watch these would appear, but here are the translations:

1. **Maintenir Haut** pour nouveau compte à rebours
2. **Maintenir Droit** pour nouveau compte à rebours
3. **Appuyer et maintenir** pour nouveau compte à rebours

Thanks!

**Comment by bhawker** [comment]
Thank you hobbe! 

Sorry about the lack of context. You probably have to pull down the latest master changes to see, but these are used for the HelpLabelText value for different devices that I just added support for. Some of the watches don't have a proper "Menu" button, so sometimes you have to hold down a button, or press a non-Menu button, so this label is just to make it clear for users of those watches what button to press.

**Comment by hobbe** [comment]
👍

**Pull request merged**
